// config.h

#define DEBUG

// === НАСТРОЙКИ FAILSAFE ===
#define FAILSAFE_TIMEOUT 500
#define FAILSAFE_CH1 PULSE_CENTER
#define FAILSAFE_CH2 PULSE_CENTER
#define FAILSAFE_CH3 PULSE_MIN
#define FAILSAFE_CH4 PULSE_CENTER
#define FAILSAFE_CH5 PULSE_MIN
#define FAILSAFE_CH6 PULSE_MIN
#define FAILSAFE_CH7 PULSE_MIN
#define FAILSAFE_CH8 PULSE_MIN